disabled = false
languageCode = "id"
languageName = "Bahasa Indonesia"
weight = 1


[params]
  displayName = "ID"
  isoCode = "id"
  rtl = false
  dateFormat = "2 January 2006"
  title = "A Developer's Note"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  copyright = "Aghits Nidallah - shiroyuki.dev ©2025"

[params.author]
  name = "Aghits Nidallah"
  image = "img/authors/aghitsnidallah.jpg"
  bio = "Halo, nama saya Aghits Nidallah 👋. Saya seorang `{full-stack,mobile}` developer, mahasiswa, dan `{manusia,robot}` yang hidup dengan menikmati kopi 24/7 ☕️."
  links = [
    { facebook = "https://facebook.com/irlnidallah" },
    { twitter = "https://twitter.com/irlnidallah" },
    { instagram = "https://instagram.com/irlnidallah" },
    { youtube = "https://www.youtube.com/@aghitsnidallah7953/" },
    { github = "https://github.com/NikarashiHatsu" },
    { linkedin = "https://www.linkedin.com/in/aghits-nidallah-9b6728221/" },
    { email = "mailto:yourlovelydev@gmail.com" },
  ]
