# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  pre = "briefcase"
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 10

[[main]]
  pre = "globe-hemisphere-east"
  name = "Website"
  pageRef = "website"
  parent = "Portfolio"
  weight = 11
  url = "/portfolio/website"

[[main]]
  pre = "android-logo"
  name = "Android"
  pageRef = "android"
  parent = "Portfolio"
  weight = 12
  url = "/portfolio/android"

[[main]]
  pre = "sidebar"
  name = "UI/UX"
  pageRef = "ui-ux"
  parent = "Portfolio"
  weight = 13
  url = "/portfolio/ui-ux"

[[main]]
  pre = "newspaper-clipping"
  name = "Artikel"
  pageRef = "artikel"
  weight = 20
  url = "/artikel"

[[main]]
  pre = "images-square"
  name = "Galeri"
  pageRef = "galeri"
  weight = 20
  url = "/galeri"

[[main]]
  pre = "option"
  name = "Lainnya"
  pageRef = "lainnya"
  weight = 20
  url = "/lainnya"

[[main]]
  pre = "graduation-cap"
  name = "Kuliah"
  parent = "Lainnya"
  pageRef = "kuliah"
  weight = 20
  url = "/lainnya/kuliah"

[[main]]
  pre = "music-notes"
  name = "Lirik Lagu"
  parent = "Lainnya"
  pageRef = "lirik-lagu"
  weight = 20
  url = "/lainnya/lirik-lagu"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/NikarashiHatsu"
  weight = 25

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/irlnidallah"
  weight = 30

#[[main]]
#  name = "Artikel"
#  parent = "In this Page"
#  pageRef = "artikel"
#  weight = 20

#[[main]]
#  name = "Lirik"
#  parent = "In this Page"
#  pageRef = "lirik"
#  weight = 20

#[[main]]
#  name = "Lirik"
#  parent = "In this Page"
#  pageRef = "lirik"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
