# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  pre = "briefcase"
  name = "Portfolio"
  weight = 10

[[main]]
  pre = "globe-hemisphere-east"
  name = "Website"
  parent = "Portfolio"
  weight = 11
  url = "/portfolio/website"

[[main]]
  pre = "android-logo"
  name = "Android"
  parent = "Portfolio"
  weight = 12
  url = "/portfolio/android"

[[main]]
  pre = "sidebar"
  name = "UI/UX"
  parent = "Portfolio"
  weight = 13
  url = "/portfolio/ui-ux"

[[main]]
  pre = "newspaper-clipping"
  name = "Artikel"
  weight = 20
  url = "/artikel"

[[main]]
  pre = "images-square"
  name = "Galeri"
  weight = 20
  url = "/galeri"

[[main]]
  name = "2024"
  parent = "Galeri"
  weight = 996
  url = "/galeri"

[[main]]
  name = "2023"
  parent = "Galeri"
  weight = 997
  url = "/galeri/2023"

[[main]]
  name = "2022"
  parent = "Galeri"
  weight = 998
  url = "/galeri/2022"

[[main]]
  name = "2021"
  parent = "Galeri"
  weight = 999
  url = "/galeri/2021"

[[main]]
  pre = "option"
  name = "Lainnya"
  weight = 20
  url = "/lainnya"

[[main]]
  pre = "graduation-cap"
  name = "Kuliah"
  parent = "Lainnya"
  weight = 20
  url = "/lainnya/kuliah"

[[main]]
  pre = "music-notes"
  name = "Lirik Lagu"
  parent = "Lainnya"
  weight = 20
  url = "/lainnya/lirik-lagu"

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/NikarashiHatsu"
  weight = 25

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/irlnidallah"
  weight = 30

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
